### ISSUE TITLE
Holopin bot setup for Dapr

### ISSUE THREAD

**Issue by botatooo** [holopin/integration-support#1]
Heya @marcduiker,

We'll be providing support in here, so feel free to ask any questions!

In regards to your previous ticket, can you just confirm that you're a member of Dapr's Holopin organization? If so, would you mind trying once more to award a badge?

**Comment by marcduiker** [comment]
Hi @botatooo , it looks like it's working! => https://github.com/dapr/docs/issues/3750#issuecomment-1744880204

I'm the owner of the Dapr Holopin org.

Any idea why it worked this time?

**Comment by botatooo** [comment]
It could have to do with the fact that we've recently made a few changes in the way the bot checks the issuing user's permissions. Previously, you'd need to have a role in the GitHub organization, but based on customer feedback we've changed it to only require being a member (or an owner in your case 🙂) of the organization on Holopin.

**Comment by marcduiker** [comment]
Excellent to hear. I think this issue can be closed now, thanks!

**Comment by botatooo** [comment]
Have a nice day!
