### ISSUE TITLE
Error when create Organization

### ISSUE THREAD

**Issue by Chhunneng** [holopin/integration-support#7]
I got this screen when creating an Organization. I think it happens when inputting long `Description` 
<img width="936" alt="Screenshot 2023-11-15 at 13 42 52" src="https://github.com/holopin/integration-support/assets/47348453/a51d4eb8-52d8-40ad-9416-77014ae0aaeb">

**Comment by elenalape** [comment]
Hello! This repo is for integration support, but we can help you out in (support@holopin.io)[mailto:support@holopin.io] :)

As a quick solution, you can use a shorter description, as that's something you'll be able to update afterwards.
